"use client";
// app/morning/page.tsx — Morning Alpha Scan
// Daily briefing generated by GitHub Actions at 02:30 UTC, stored in Supabase.

import { useQuery } from "@tanstack/react-query";
import { timeAgo, formatUsd, formatPct } from "@/lib/utils";
import { QueryProvider } from "@/components/query-provider";

const S = {
  page:  { padding: "28px", maxWidth: "900px", margin: "0 auto" },
  card:  { background: "#0f0f0f", border: "1px solid rgba(180,180,180,0.12)", borderRadius: "10px", overflow: "hidden" as const },
  hdr:   { borderBottom: "1px solid rgba(180,180,180,0.06)", padding: "16px 20px", display: "flex", alignItems: "center", gap: "12px" },
  label: { fontSize: "10px", fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase" as const, color: "rgba(227,227,227,0.38)" },
  muted: { color: "rgba(227,227,227,0.38)", fontSize: "11px" },
  body:  { fontSize: "13px", color: "rgba(227,227,227,0.8)", lineHeight: 1.7 },
};

interface MorningScan {
  generated_at: string;
  regime: string;
  btc_return_24h: number;
  top_movers: Array<{ coin: string; notional: string; direction: string }>;
  top_signals: Array<{ recipe: string; coin: string; direction: string; ev: number | null }>;
  cohort_health: { active_wallets: number; avg_score: number; wallets_in_profit: number };
  top_wallets: Array<{ address: string; score: number; pnl: string }>;
  summary: string;
  watch_list: string[];
}

function MorningScanInner() {
  const { data, isLoading } = useQuery<MorningScan>({
    queryKey: ["morning-scan"],
    queryFn:  () => fetch("/api/morning-scan").then((r) => r.json()),
    refetchInterval: 5 * 60_000, // refresh every 5 min (it's a daily doc)
  });

  if (isLoading || !data) return <div style={{ padding: "28px", ...S.muted }}>Loading morning scan…</div>;

  const regimeColor = data.regime === "BULL" ? "#4ade80" : data.regime === "BEAR" ? "#f87171" : "#9ca3af";

  return (
    <div style={S.page}>
      <div style={{ marginBottom: "24px", display: "flex", alignItems: "baseline", gap: "16px" }}>
        <div>
          <h1 style={{ fontSize: "18px", fontWeight: 700, color: "#e3e3e3" }}>Morning Alpha Scan</h1>
          <p style={S.muted}>Generated daily at 02:30 UTC · {timeAgo(data.generated_at)}</p>
        </div>
        <div style={{ marginLeft: "auto", fontSize: "11px", fontWeight: 700, padding: "4px 10px", borderRadius: "4px",
          background: `${regimeColor}14`, color: regimeColor, border: `1px solid ${regimeColor}30` }}>
          {data.regime} · BTC {data.btc_return_24h >= 0 ? "+" : ""}{formatPct(data.btc_return_24h)}
        </div>
      </div>

      {/* Summary */}
      <div style={{ ...S.card, padding: "20px 24px", marginBottom: "16px" }}>
        <div style={{ ...S.label, marginBottom: "12px" }}>Daily Briefing</div>
        <p style={S.body}>{data.summary}</p>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "16px" }}>
        {/* Cohort health */}
        <div style={S.card}>
          <div style={S.hdr}><span style={S.label}>Cohort Health</span></div>
          <div style={{ padding: "16px 20px" }}>
            {[
              { label: "Active Wallets",    value: `${data.cohort_health.active_wallets}` },
              { label: "Avg Score",         value: data.cohort_health.avg_score.toFixed(2) },
              { label: "Wallets in Profit", value: `${data.cohort_health.wallets_in_profit}` },
            ].map(({ label, value }) => (
              <div key={label} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid rgba(180,180,180,0.06)" }}>
                <span style={S.muted}>{label}</span>
                <span style={{ fontSize: "13px", fontWeight: 600 }}>{value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Watch list */}
        <div style={S.card}>
          <div style={S.hdr}><span style={S.label}>Today's Watch List</span></div>
          <div style={{ padding: "16px 20px", display: "flex", flexWrap: "wrap" as const, gap: "8px" }}>
            {data.watch_list.map((coin) => (
              <a key={coin} href={`/deep-dive?coin=${coin}`}
                style={{ padding: "5px 12px", background: "rgba(96,96,96,0.1)", border: "1px solid rgba(96,96,96,0.3)", borderRadius: "4px", fontSize: "12px", fontWeight: 700, color: "#e3e3e3", textDecoration: "none" }}>
                {coin}
              </a>
            ))}
          </div>
        </div>
      </div>

      {/* Top signals */}
      <div style={{ ...S.card, marginBottom: "16px" }}>
        <div style={S.hdr}><span style={S.label}>Top Signals Yesterday</span></div>
        {data.top_signals.length === 0 ? (
          <div style={{ padding: "24px", textAlign: "center", ...S.muted }}>No signals in the last 24h</div>
        ) : (
          data.top_signals.map((sig, i) => {
            const dirColor = sig.direction === "LONG" ? "#4ade80" : sig.direction === "SHORT" ? "#f87171" : "#9ca3af";
            return (
              <div key={i} style={{ padding: "12px 20px", borderBottom: "1px solid rgba(180,180,180,0.06)", display: "flex", alignItems: "center", gap: "12px" }}>
                <div style={{ width: "7px", height: "7px", borderRadius: "50%", background: dirColor, flexShrink: 0 }} />
                <span style={{ fontSize: "12px", fontWeight: 600 }}>{sig.recipe}</span>
                <span style={{ fontSize: "12px", color: dirColor, fontWeight: 700 }}>{sig.coin}</span>
                <span style={{ fontSize: "10px", color: dirColor, letterSpacing: "0.08em" }}>{sig.direction}</span>
                {sig.ev != null && (
                  <span style={{ marginLeft: "auto", fontSize: "11px", color: "#606060", fontWeight: 600 }}>EV {(sig.ev * 100).toFixed(0)}</span>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Top movers */}
      <div style={S.card}>
        <div style={S.hdr}><span style={S.label}>Top Cohort Movers (24h)</span></div>
        {data.top_movers.map((m, i) => {
          const dirColor = m.direction === "LONG" ? "#4ade80" : "#f87171";
          return (
            <div key={i} style={{ padding: "12px 20px", borderBottom: "1px solid rgba(180,180,180,0.06)", display: "flex", alignItems: "center", gap: "12px" }}>
              <span style={{ fontSize: "13px", fontWeight: 700 }}>{m.coin}</span>
              <span style={{ fontSize: "10px", fontWeight: 700, padding: "2px 7px", borderRadius: "4px",
                background: `${dirColor}14`, color: dirColor, border: `1px solid ${dirColor}25` }}>
                {m.direction}
              </span>
              <span style={{ marginLeft: "auto", fontSize: "12px", fontVariantNumeric: "tabular-nums" }}>{m.notional}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default function MorningScanPage() {
  return <QueryProvider><MorningScanInner /></QueryProvider>;
}
